definitions:
  handler.LoginRequest:
    properties:
      userName:
        type: string
    type: object
  handler.Result:
    properties:
      answer:
        type: string
      questionId:
        type: string
    type: object
  handler.SubmitTestRequest:
    properties:
      results:
        items:
          $ref: '#/definitions/handler.Result'
        type: array
    type: object
  model.Question:
    properties:
      answer:
        type: string
      category:
        type: string
      content:
        type: string
      createdAt:
        type: string
      difficulty:
        type: integer
      id:
        type: integer
      options:
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
  model.User:
    properties:
      avatarURL:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      nickname:
        type: string
      openID:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用户通过微信登录
      parameters:
      - description: 登录请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - 用户
  /questions:
    get:
      consumes:
      - application/json
      description: 根据类目和类型获取题目
      parameters:
      - description: 题目类目
        in: query
        name: category
        required: true
        type: string
      - description: 题目类型
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Question'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取题目
      tags:
      - 题目
  /submit-test:
    post:
      consumes:
      - application/json
      description: 提交测试结果
      parameters:
      - description: 测试结果
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.SubmitTestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 提交测试
      tags:
      - 测试
swagger: "2.0"
